language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - DBMIGRATE_PATH=./examples/migrations/

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsqlcipher-dev

services:
  - mysql
  - postgresql
  - sqlite3

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS migrate;'
  - psql -c 'create database migrate;' -U postgres
  - touch migrate.db
  - chmod 777 migrate.db

script:
  - cd dbmigrate-lib && cargo test
  - cd ../dbmigrate && cargo build
  - DBMIGRATE_URL=postgres://postgres@localhost/migrate cargo run status
  - DBMIGRATE_URL=mysql://travis@localhost/migrate cargo run status
  - DBMIGRATE_URL=sqlite://`pwd`/migrate.db cargo run status
  # On Ubuntu 14.04 (Trusty), add a locally-built version of SQLCipher to the LD_LIBRARY_PATH
  - source ../.travis-trusty-sqlcipher-helper.bash
  - DBMIGRATE_URL=sqlcipher://user:password@localhost`pwd`/migrate.sqlcipher cargo run --no-default-features --features sqlcipher_support -- status
