language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - DBMIGRATE_PATH=./examples/migrations/

notifications:
  email: false

services:
  - mysql
  - postgresql
  - sqlite3

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS migrate;'
  - psql -c 'create database migrate;' -U postgres
  - touch migrate.db
  - chmod 777 migrate.db

script:
  - cd dbmigrate-lib && cargo test
  - cd ../dbmigrate && cargo build
  - DBMIGRATE_URL=postgres://postgres@localhost/migrate cargo run status
  - DBMIGRATE_URL=mysql://travis@localhost/migrate cargo run status
  - DBMIGRATE_URL=sqlite://`pwd`/migrate.db cargo run status
